### ISSUE TITLE
Module Not Found Error Using Gulp with 3.0

### ISSUE THREAD

**Issue by peilingjiang** [postcss/postcss-scss#112]
Hi, I'm having the following error after bump the version from 2.1.1 to 3.0 -

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../node_modules/postcss-scss/lib/scss-syntax.mjs' imported from .../gulpfile.js
Did you mean to import postcss-scss/lib/scss-syntax.js?
```

Any ideas or suggestions on how to fix it? Thanks!

**Comment by ai** [comment]
Show your Gulpfile

**Comment by peilingjiang** [comment]
Thank you!

```
import scss from 'postcss-scss'

task('css', function () {
  return src(['./src/**/*.css', '!./src/postcss/**/*.css'])
    .pipe(
      postcss(
        [
          // Plugins...
        ],
        {
          syntax: scss,
        }
      )
    )
    .pipe(dest('./src/postcss'))
})
```

**Comment by ai** [comment]
Thanks for the report. Fixed in 3.0.1.
